name: Devops Workflow

on:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of code
        uses: action/checkout@v3

      - name: Show the message
        run: "Hello, World Devops!"