name: Devops Workflow

on:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Show the message
        run: "Hello, World Devops!"